---
- name: "copy all file"
  copy:
    src: backend
    dest: ~/udapeople/backend
    backup: yes

- name: "run backend server"
  become: true
  command: "npm run start:prod"
  async: 45
  poll: 0
  args:
    chdir: ~/udapeople/backend