---
- name: "copy all file"
  copy:
    src: dist/
    dest: ~/
    backup: yes

# - name: Install BE packages based on package.json.
#   npm:
#     path: ~/
#     state: present

# - name: "build backend server"
#   become: true
#   command: "npm run build"

# - name: "run backend server"
#   become: true
#   command: "npm run start:prod"
#   async: 45
#   poll: 0

- name: "run backend server"
  become: true
  command: "pm2 start npm -- start:prod"