---
- name: "git clone repo"
  become: true
  git:
    repo: "https://github.com/Jessinra/cdond-c3-projectstarter.git"
    dest: "~/udapeople"
    clone: yes

- name: Install BE packages based on package.json.
  npm:
    path: ~/udapeople/backend
    state: present

- name: "build backend server"
  become: true
  command: "npm run build"
  args:
    chdir: ~/udapeople/backend

- name: "run backend server"
  become: true
  command: "npm run start"
  async: 45
  poll: 0
  args:
    chdir: ~/udapeople/backend